#!/usr/bin/python
from team_paths import team_paths as tp
import cgi, cgitb

#unfortunately has to go first; see bottom for interesting bits
#I put this here so I didn't have to open the illinois.html file 7 zillion times
def get_html():
    return """
<form action="illinois.py" method="GET">
<select name="team">
<option value="air force">Air Force
<option value="akron">Akron
<option value="alabama">Alabama
<option value="alabama a&m">Alabama A&M
<option value="alabama st.">Alabama St.
<option value="alaska anchorage">Alaska Anchorage
<option value="albany">Albany
<option value="alcorn st.">Alcorn St.
<option value="american">American
<option value="appalachian st.">Appalachian St.
<option value="arizona">Arizona
<option value="arizona st.">Arizona St.
<option value="arkansas">Arkansas
<option value="arkansas little rock">Arkansas Little Rock
<option value="arkansas pine bluff">Arkansas Pine Bluff
<option value="arkansas st.">Arkansas St.
<option value="army">Army
<option value="auburn">Auburn
<option value="austin peay">Austin Peay
<option value="ball st.">Ball St.
<option value="baylor">Baylor
<option value="belmont">Belmont
<option value="bethune cookman">Bethune Cookman
<option value="binghamton">Binghamton
<option value="birmingham southern">Birmingham Southern
<option value="bluefield">Bluefield
<option value="boise st.">Boise St.
<option value="boston college">Boston College
<option value="boston university">Boston University
<option value="bowling green">Bowling Green
<option value="bradley">Bradley
<option value="brigham young">Brigham Young
<option value="brown">Brown
<option value="bucknell">Bucknell
<option value="buffalo">Buffalo
<option value="butler">Butler
<option value="cal davis">Cal Davis
<option value="cal irvine">Cal Irvine
<option value="cal poly">Cal Poly
<option value="cal riverside">Cal Riverside
<option value="cal santa barbara">Cal Santa Barbara
<option value="cal st. fullerton">Cal St. Fullerton
<option value="cal st. northridge">Cal St. Northridge
<option value="california">California
<option value="campbell">Campbell
<option value="canisius">Canisius
<option value="centenary">Centenary
<option value="central connecticut">Central Connecticut
<option value="central florida">Central Florida
<option value="central michigan">Central Michigan
<option value="chaminade">Chaminade
<option value="charleston southern">Charleston Southern
<option value="charlotte">Charlotte
<option value="chattanooga">Chattanooga
<option value="chicago st.">Chicago St.
<option value="cincinnati">Cincinnati
<option value="clemson">Clemson
<option value="cleveland st.">Cleveland St.
<option value="coastal carolina">Coastal Carolina
<option value="colgate">Colgate
<option value="college of charleston">College Of Charleston
<option value="colorado">Colorado
<option value="colorado st.">Colorado St.
<option value="columbia">Columbia
<option value="connecticut">Connecticut
<option value="coppin st.">Coppin St.
<option value="cornell">Cornell
<option value="creighton">Creighton
<option value="dartmouth">Dartmouth
<option value="davidson">Davidson
<option value="dayton">Dayton
<option value="delaware">Delaware
<option value="delaware st.">Delaware St.
<option value="denver">Denver
<option value="depaul">Depaul
<option value="detroit">Detroit
<option value="drake">Drake
<option value="drexel">Drexel
<option value="duke">Duke
<option value="duquesne">Duquesne
<option value="east carolina">East Carolina
<option value="east tennessee st.">East Tennessee St.
<option value="eastern illinois">Eastern Illinois
<option value="eastern kentucky">Eastern Kentucky
<option value="eastern michigan">Eastern Michigan
<option value="eastern washington">Eastern Washington
<option value="elon">Elon
<option value="evansville">Evansville
<option value="fairfield">Fairfield
<option value="fairleigh dickinson">Fairleigh Dickinson
<option value="florida">Florida
<option value="florida a&m">Florida A&M
<option value="florida atlantic">Florida Atlantic
<option value="florida international">Florida International
<option value="florida st.">Florida St.
<option value="fordham">Fordham
<option value="fort lewis">Fort Lewis
<option value="fresno st.">Fresno St.
<option value="furman">Furman
<option value="gardner webb">Gardner Webb
<option value="george mason">George Mason
<option value="george washington">George Washington
<option value="georgetown">Georgetown
<option value="georgia">Georgia
<option value="georgia southern">Georgia Southern
<option value="georgia st.">Georgia St.
<option value="georgia tech">Georgia Tech
<option value="gettysburg">Gettysburg
<option value="gonzaga">Gonzaga
<option value="grambling">Grambling
<option value="hampden sydney">Hampden Sydney
<option value="hampton">Hampton
<option value="hartford">Hartford
<option value="harvard">Harvard
<option value="hawaii">Hawaii
<option value="high point">High Point
<option value="hofstra">Hofstra
<option value="holy cross">Holy Cross
<option value="houston">Houston
<option value="howard">Howard
<option value="idaho">Idaho
<option value="idaho st.">Idaho St.
<option value="illinois">Illinois
<option value="illinois chicago">Illinois Chicago
<option value="illinois st.">Illinois St.
<option value="indiana">Indiana
<option value="indiana st.">Indiana St.
<option value="iona">Iona
<option value="iowa">Iowa
<option value="iowa st.">Iowa St.
<option value="iupu fort wayne">Iupu Fort Wayne
<option value="iupui">Iupui
<option value="jackson st.">Jackson St.
<option value="jacksonville">Jacksonville
<option value="jacksonville st.">Jacksonville St.
<option value="james madison">James Madison
<option value="kansas">Kansas
<option value="kansas st.">Kansas St.
<option value="kent st.">Kent St.
<option value="kentucky">Kentucky
<option value="la salle">La Salle
<option value="lafayette">Lafayette
<option value="lamar">Lamar
<option value="lander">Lander
<option value="lehigh">Lehigh
<option value="liberty">Liberty
<option value="lipscomb">Lipscomb
<option value="long beach st.">Long Beach St.
<option value="long island">Long Island
<option value="longwood">Longwood
<option value="louisiana lafayette">Louisiana Lafayette
<option value="louisiana monroe">Louisiana Monroe
<option value="louisiana st.">Louisiana St.
<option value="louisiana tech">Louisiana Tech
<option value="louisville">Louisville
<option value="loyola chicago">Loyola Chicago
<option value="loyola marymount">Loyola Marymount
<option value="loyola md">Loyola Md
<option value="maine">Maine
<option value="manhattan">Manhattan
<option value="marist">Marist
<option value="marquette">Marquette
<option value="marshall">Marshall
<option value="maryland">Maryland
<option value="maryland eastern shore">Maryland Eastern Shore
<option value="massachusetts">Massachusetts
<option value="mcneese st.">Mcneese St.
<option value="md baltimore county">Md Baltimore County
<option value="memphis">Memphis
<option value="mercer">Mercer
<option value="miami fl">Miami Fl
<option value="miami oh">Miami Oh
<option value="michigan">Michigan
<option value="michigan st.">Michigan St.
<option value="middle tennessee">Middle Tennessee
<option value="minnesota">Minnesota
<option value="mississippi">Mississippi
<option value="mississippi st.">Mississippi St.
<option value="mississippi valley st.">Mississippi Valley St.
<option value="missouri">Missouri
<option value="missouri kansas city">Missouri Kansas City
<option value="monmouth">Monmouth
<option value="montana">Montana
<option value="montana st.">Montana St.
<option value="morehead st.">Morehead St.
<option value="morgan st.">Morgan St.
<option value="mount st. mary's">Mount St. Mary'S
<option value="murray st.">Murray St.
<option value="navy">Navy
<option value="nc asheville">Nc Asheville
<option value="nc greensboro">Nc Greensboro
<option value="nc wilmington">Nc Wilmington
<option value="nebraska">Nebraska
<option value="nevada">Nevada
<option value="nevada las vegas">Nevada Las Vegas
<option value="new hampshire">New Hampshire
<option value="new mexico">New Mexico
<option value="new mexico st.">New Mexico St.
<option value="new orleans">New Orleans
<option value="niagara">Niagara
<option value="nicholls st.">Nicholls St.
<option value="norfolk st.">Norfolk St.
<option value="north carolina">North Carolina
<option value="north carolina a&t">North Carolina A&T
<option value="north carolina st.">North Carolina St.
<option value="north texas">North Texas
<option value="northeastern">Northeastern
<option value="northern arizona">Northern Arizona
<option value="northern colorado">Northern Colorado
<option value="northern illinois">Northern Illinois
<option value="northern iowa">Northern Iowa
<option value="northwestern">Northwestern
<option value="northwestern st.">Northwestern St.
<option value="notre dame">Notre Dame
<option value="oakland">Oakland
<option value="ohio">Ohio
<option value="ohio st.">Ohio St.
<option value="oklahoma">Oklahoma
<option value="oklahoma st.">Oklahoma St.
<option value="old dominion">Old Dominion
<option value="oral roberts">Oral Roberts
<option value="oregon">Oregon
<option value="oregon st.">Oregon St.
<option value="pacific">Pacific
<option value="penn st.">Penn St.
<option value="pennsylvania">Pennsylvania
<option value="pepperdine">Pepperdine
<option value="pittsburgh">Pittsburgh
<option value="portland">Portland
<option value="portland st.">Portland St.
<option value="prairie view a&m">Prairie View A&M
<option value="princeton">Princeton
<option value="providence">Providence
<option value="purdue">Purdue
<option value="quinnipiac">Quinnipiac
<option value="radford">Radford
<option value="rhode island">Rhode Island
<option value="rice">Rice
<option value="richmond">Richmond
<option value="rider">Rider
<option value="robert morris">Robert Morris
<option value="rutgers">Rutgers
<option value="sacramento st.">Sacramento St.
<option value="sacred heart">Sacred Heart
<option value="saint joseph's">Saint Joseph'S
<option value="sam houston st.">Sam Houston St.
<option value="samford">Samford
<option value="san diego">San Diego
<option value="san diego st.">San Diego St.
<option value="san francisco">San Francisco
<option value="san jose st.">San Jose St.
<option value="santa clara">Santa Clara
<option value="seton hall">Seton Hall
<option value="siena">Siena
<option value="south alabama">South Alabama
<option value="south carolina">South Carolina
<option value="south carolina st.">South Carolina St.
<option value="south dakota st.">South Dakota St.
<option value="south florida">South Florida
<option value="southeast missouri st.">Southeast Missouri St.
<option value="southeastern louisiana">Southeastern Louisiana
<option value="southern">Southern
<option value="southern california">Southern California
<option value="southern illinois">Southern Illinois
<option value="southern methodist">Southern Methodist
<option value="southern mississippi">Southern Mississippi
<option value="southern utah">Southern Utah
<option value="southwest missouri st.">Southwest Missouri St.
<option value="st. bonaventure">St. Bonaventure
<option value="st. francis ny">St. Francis Ny
<option value="st. francis pa">St. Francis Pa
<option value="st. john's">St. John'S
<option value="st. louis">St. Louis
<option value="st. mary's">St. Mary'S
<option value="st. peter's">St. Peter'S
<option value="stanford">Stanford
<option value="stephen f. austin">Stephen F. Austin
<option value="stetson">Stetson
<option value="stony brook">Stony Brook
<option value="syracuse">Syracuse
<option value="temple">Temple
<option value="tennessee">Tennessee
<option value="tennessee martin">Tennessee Martin
<option value="tennessee st.">Tennessee St.
<option value="tennessee tech">Tennessee Tech
<option value="texas">Texas
<option value="texas a&m">Texas A&M
<option value="texas a&m corpus chris">Texas A&M Corpus Chris
<option value="texas arlington">Texas Arlington
<option value="texas christian">Texas Christian
<option value="texas el paso">Texas El Paso
<option value="texas pan american">Texas Pan American
<option value="texas san antonio">Texas San Antonio
<option value="texas southern">Texas Southern
<option value="texas st.">Texas St.
<option value="texas tech">Texas Tech
<option value="the citadel">The Citadel
<option value="toledo">Toledo
<option value="towson">Towson
<option value="troy">Troy
<option value="tulane">Tulane
<option value="tulsa">Tulsa
<option value="uab">Uab
<option value="ucla">Ucla
<option value="utah">Utah
<option value="utah st.">Utah St.
<option value="utah valley st.">Utah Valley St.
<option value="valparaiso">Valparaiso
<option value="vanderbilt">Vanderbilt
<option value="vermont">Vermont
<option value="villanova">Villanova
<option value="virginia">Virginia
<option value="virginia commonwealth">Virginia Commonwealth
<option value="virginia military inst">Virginia Military Inst
<option value="virginia tech">Virginia Tech
<option value="wagner">Wagner
<option value="wake forest">Wake Forest
<option value="washington">Washington
<option value="washington st.">Washington St.
<option value="weber st.">Weber St.
<option value="west virginia">West Virginia
<option value="western carolina">Western Carolina
<option value="western illinois">Western Illinois
<option value="western kentucky">Western Kentucky
<option value="western michigan">Western Michigan
<option value="wichita st.">Wichita St.
<option value="william & mary">William & Mary
<option value="winthrop">Winthrop
<option value="wisconsin">Wisconsin
<option value="wisconsin green bay">Wisconsin Green Bay
<option value="wisconsin milwaukee">Wisconsin Milwaukee
<option value="wisconsin parkside">Wisconsin Parkside
<option value="wofford">Wofford
<option value="wright st.">Wright St.
<option value="wyoming">Wyoming
<option value="xavier">Xavier
<option value="yale">Yale
<option value="youngstown st.">Youngstown St.
</select><input type="submit" value="submit"></form>
"""

cgitb.enable()
form = cgi.FieldStorage()
team = form['team'].value
print "Content-Type: text/html\n"
print """<html><head><title>Illinois Number Calculator</title></head>
<body><h1>%s</h1><p>\nHas an Illinois number of: <b>%d</b>:<p>\n%s<br><br><br>
Find another team's Illinois number:%s</body>""" % \
(team.title(), tp[team].count('\n'), tp[team].replace('\n', '<br>'), get_html())

