VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CEvents"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public WithEvents PPEvents As Application
Attribute PPEvents.VB_VarHelpID = -1

Private Sub PPEvents_NewPresentation(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_PresentationClose(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_NewSlide(ByVal Sld As Slide)
    
End Sub
Private Sub PPEvents_PresentationOpen(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_PresentationPrint(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_PresentationSave(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_SlideShowBegin(ByVal Wn As SlideShowWindow)
    
End Sub
Private Sub PPEvents_SlideShowEnd(ByVal Pres As Presentation)
    
End Sub
Private Sub PPEvents_SlideShowNextBuild(ByVal Wn As SlideShowWindow)
    
End Sub
Private Sub PPEvents_SlideShowNextSlide(ByVal Wn As SlideShowWindow)
    
End Sub
Private Sub PPEvents_WindowActivate(ByVal Pres As Presentation, ByVal Wn As DocumentWindow)
    
End Sub
Private Sub PPEvents_WindowBeforeDoubleClick(ByVal Sel As Selection, Cancel As Boolean)
    
End Sub
Private Sub PPEvents_WindowBeforeRightClick(ByVal Sel As Selection, Cancel As Boolean)
    
End Sub
Private Sub PPEvents_WindowDeactivate(ByVal Pres As Presentation, ByVal Wn As DocumentWindow)
    
End Sub
Private Sub PPEvents_SelectionChange(ByVal Sel As Selection)
    
End Sub

