application: sparklines-bitworking
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /spark.js
  static_files: spark.js 
  upload: spark.js 

- url: /spark.cgi?.*
  script: spark.py


